# Dify SDK 配置文件示例

# 基础配置
base_url: "https://api.dify.ai"
auth_type: "bearer"
token: "${DIFY_TOKEN}"  # 从环境变量读取
timeout: "30s"
max_retries: 3

# 工作空间配置
workspace_id: "${DIFY_WORKSPACE_ID}"

# 日志配置
log_level: "info"  # debug, info, warn, error, fatal
log_format: "json"  # json, text
log_output: "stdout"  # stdout, stderr, file
log_file: "logs/dify-sdk.log"

# 监控配置
enable_metrics: true
metrics_port: 8080
health_check: true

# 连接池配置
max_idle_conns: 100
max_idle_conns_per_host: 10
idle_conn_timeout: "90s"